<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    
    <xacro:include filename="robot_include.xacro" />

    <link name="world"/>

    <joint name="base_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="1.5 1.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
            <mass value="12.0"/>
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
            <material name="green">
                <color rgba="0.2 1.0 0.2 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
        </collision>
    </link>

    <joint name="slider_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="slider_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="2" velocity="100" effort="100.0"/>
        <origin xyz="-1.25 0 0.1" rpy="0 0 0"/>
    </joint>

    <link name="slider_link">
        <visual>
            <origin xyz="0.0 0.0 0.075" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.5 0.25 0.15"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.075" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.5 0.25 0.15"/>
            </geometry>
        </collision>
    </link>

    <joint name="arm_joint" type="revolute">
        <parent link="slider_link"/>
        <child link="arm_link"/>
        <axis xyz="0 -1 0"/>
        <limit lower="0" upper="${pi/2}" velocity="100.0" effort="100.0"/>
        <origin xyz="0.25 0 0.15" rpy="0 0 0"/>
    </joint>

    <xacro:property name="arm_length" value="1" />
    <xacro:property name="arm_radius" value="0.1" />
    <link name="arm_link">
        <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="arm_link"/>
        <child link="camera_link"/>
        <origin xyz="${arm_length} 0.0 ${arm_radius + 0.075}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="camera_link">
        <visual>
            <origin xyz="-0.03 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.06 0.15 0.15"/>
            </geometry>
            <material name="white"/>
        </visual>
        <visual>
            <origin xyz="0.03 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
            <geometry>
                <cylinder radius="0.06" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.12 0.15 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <xacro:include filename="example_gazebo.xacro" />



</robot>